### PR TITLE
Misc. fixes

### PR DESCRIPTION
**Pull request by chipzoller**
Fixes and/or improves on several lab examples, mostly minor.

### CODE REVIEW

**Comment by chipzoller** [comment]
@cerebro1, please review

**Comment by chipzoller** [comment]
or cc @eeganlf

**Comment by cerebro1** [comment]
> @cerebro1, please review

Sure @chipzoller
I am AFK currently, will take it up on Monday.

**Comment by cerebro1** [comment]
Looks good to merge. Contains minor misc changes around indentation and fixing a typo in the job name. Verified using playground the recommended changes.

**Pull request merged**
